#!/bin/bash

source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh > /tmp/fluxmeter_log_beamlosses_${1} 2>&1

# FCCDetectors
export FCCDETECTORS=${HOME}/FCC/FCCDetectors/install/share/FCCDetectors
export LD_LIBRARY_PATH=${HOME}/FCC/FCCDetectors/install/lib64:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${HOME}/FCC/FCCDetectors/install/lib:${LD_LIBRARY_PATH}
export PYTHONPATH=${HOME}/FCC/FCCDetectors/install/python:${PYTHONPATH}
# k4SimGeant4
export k4SimGeant4_DIR=${HOME}/FCC/k4SimGeant4/install
export K4SIMGEANT4=${HOME}/FCC/k4SimGeant4/install
export PATH=${HOME}/FCC/k4SimGeant4/install/scripts:${PATH}
export LD_LIBRARY_PATH=${HOME}/FCC/k4SimGeant4/install/lib:${LD_LIBRARY_PATH}
export PYTHONPATH=${HOME}/FCC/k4SimGeant4/install/python:${PYTHONPATH}
# k4Gen
export k4Gen_DIR=${HOME}/FCC/k4gen/install
export LD_LIBRARY_PATH=${HOME}/FCC/k4Gen/install/lib:${LD_LIBRARY_PATH}
export PYTHONPATH=${HOME}/FCC/k4Gen/install/python:${PYTHONPATH}

k4run /home/jsmiesko/FCC/fcc_radiation/run/runCLD_fluxmeter_beamlosses.py \
      --MDIReader.MDIFilename ../input/mdi_losses_coll_z_v529/mdi_losses_IPA_10p_${1}.dat \
      --SimG4Svc.seedValue 562${1} \
      --out.filename output_fluxmeter_beamlosses_z_ipa_${1}.root >> /tmp/fluxmeter_log_beamlosses_${1} 2>&1
